feat: add format options for report output
lirantal/lockfile-lint pull request #134
Opened 2022-07-27 08:52 UTC by rheimus

## Description

Adds a flag for setting what type of report output is desired
- plain - raw text essentially without colors/symbols
- pretty - (default) same as before with colors symbols

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

#133 

## Motivation and Context

Sadly many environments and parsing tools don't like fancy characters or color sequences, this just gives an alternative friendly output for more basic systems.

## How Has This Been Tested?

- Tested manually under WSL windows
- Unit tests added for error output

I could add tests for the 'success' (no errors) path if desired.

## Screenshots (if appropriate):

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun
🦍 <-- cute animal

2022-07-27 08:55 UTC, rheimus commented
Interesting note, this repo does not work under native windows, has problems spawning processes for the unit tests.

2022-07-29 21:30 UTC, lirantal commented
We'll look into it shortly @rheimus 🙏🏼

2022-08-09 11:21 UTC, lirantal requested changes

2022-08-09 11:21 UTC, lirantal commented on packages/lockfile-lint/__tests__/cli.test.js
> +  test('Unspecified output has symbols and color', done => {
```suggestion
  test('default usage has output with symbols and color', done => {
```

2022-08-09 11:21 UTC, lirantal commented on packages/lockfile-lint/__tests__/cli.test.js
> +  test('Format pretty has symbols and color', done => {
```suggestion
  test('When using --pretty formatting then output has symbols and color', done => {
```

2022-08-09 11:21 UTC, lirantal commented on packages/lockfile-lint/__tests__/cli.test.js
> +  test('Format plain does not have symbols or color', done => {
```suggestion
  test('hen using --plain formatting then output does not have symbols or color', done => {
```

2022-08-09 11:30 UTC, lirantal commented
@rheimus looks good to me to land. Thank you for refactoring to support the error/warn/success functions and building this plain/pretty capability into the lockfile-lint CLI. Much appreciated 👏🙏🏼

2022-08-10 05:33 UTC, rheimus commented
Applied the requested changes and fixed a typo in the plain formatting test set.

2022-08-10 09:28 UTC, lirantal approved these changes

2022-08-10 09:29 UTC, lirantal commented
Looks great, thank you!

2022-08-10 09:47 UTC, merged